### ISSUE TITLE
Trying to create an oracle driver jdbc library

### ISSUE THREAD

**Issue by jvivallos** [syndesisio/syndesis-extensions#104]
I was getting an error with the sindesis version, after solving it changing the sindesis version from 1.12-SNAPSHOT to 1.12.0.

I can't get ./mvnw -pl :syndesis-library-jdbc-driver clean package to work.

I consistently get the following error

[ERROR] Failed to execute goal io.syndesis.extension:extension-maven-plugin:1.12.0:repackage-extension (default) on project syndesis-library-jdbc-driver: Execution default of goal io.syndesis.extension:extension-maven-plugin:1.12.0:repackage-extension failed: Unable to invoke onlyOne([Ljava.lang.Class;@a5f18edc) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@6c1c324c: InvocationTargetException: Could not create new service instance: org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector -> [Help 1]

Although the .jar is being generated it does not work on the Fuse Online instance I have on Openshift.

**Comment by zregvart** [comment]
Hi @jvivallos, several issues to unpack here. If you're using Fuse Online, then you need to make sure that the version given in [`syndesis.version`](https://github.com/syndesisio/syndesis-extensions/blob/7efb8119cb35390ba9beb5028ba1f932e61343ff/pom.xml#L31) property corresponds to your environment. For this there is a [Groovy script](https://github.com/syndesisio/syndesis-extensions/blob/7efb8119cb35390ba9beb5028ba1f932e61343ff/pom.xml#L116-L182) that dynamically fetches the version from a running instance [if `syndesisServerUrl` property is provided](https://github.com/syndesisio/syndesis-extensions#build-with-automatic-syndesis-version-detection).

Minor releases of Maven can introduce breaking API changes which lead to issues like what you're seeing. In 7efb8119cb35390ba9beb5028ba1f932e61343ff (few minutes ago) Maven version was updated, which might help in your case as well.

Another issue with Oracle drivers is that they have recently been uploaded to Maven Central, and appeared in Spring Boot BOM as a managed dependency. The repackaging removes all managed dependencies from the resulting JAR file, so you must use different Maven coordinates to avoid that and get the driver JAR packaged inside of the JDBC extension library. Best use the `system` scope and `systemPath` to achieve that.

**Comment by jvivallos** [comment]
What I've been using on the pom is

<dependencies>
    <dependency>
      <groupId>com.oracle.ojdbc</groupId>
      <artifactId>jdbc-driver</artifactId>
      <version>1.0</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/lib/ojdbc7.jar</systemPath>
    </dependency>
  </dependencies>

then I run  

mvn clean install -DsyndesisServerUrl=https://syndesis... (our sindesis server)

and finally 

./mvnw -pl :syndesis-library-jdbc-driver clean package

This final step is what throws an error, and even though it generates a .jar I cannot make it work inside Fuse

**Comment by zregvart** [comment]
The build needs to succeed without errors for the JAR file to be valid. In the previous comment I've detailed the steps on how I managed to build a valid JAR file for a JDBC library extension. Also pay close attention to the last paragraph in that comment.
