### ISSUE TITLE
Names of Extensions within readme files are mixed up

### ISSUE THREAD

**Issue by honghuac** [syndesisio/syndesis-extensions#45]
The names of the extensions, found in their respective readme files, are mixed up:
1) Wrongly named as "loop" - https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-extension-body
2) Wrongly named as "set body" - https://github.com/syndesisio/syndesis-extensions/tree/master/syndesis-extension-manage-headers

**Comment by oscerd** [comment]
Fixed
