### ISSUE TITLE
Offer a workflow to pick up the version of the BOM automatically from a Syndesis endpoint

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis-extensions#54]
currently we are pointing to master. anyone that wants to build the extensions, need to either modify pom.xml or pass a build time variable.

this will still be required, unless we provide helper scripts but we can improve the workflow just asking the url of a syndesis instance, and extract it on our own.

@lburgazzoli @oscerd wdyt?

**Comment by oscerd** [comment]
+1

**Comment by lburgazzoli** [comment]
I guess this is similar to https://github.com/syndesisio/syndesis/issues/636

**Comment by valdar** [comment]
The offered workflow is nothing fancy: if a `syndesisServerUrl` is present that is used to `GET syndesisServerUrl/api/v1/version` and the returned value is set, for the current maven build to the `syndesis.version` property.
