### ISSUE TITLE
Maven archetype to ease extension project setup

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis-extensions#88]
The presence of a maven archetype would ease the development of an extension. We can think of a different one for each extension type.

**Comment by lburgazzoli** [comment]
Some archetypes are available here: https://github.com/syndesisio/syndesis/tree/master/app/extension/archetype

**Comment by squakez** [comment]
Great! Thanks @lburgazzoli , I'll include this in the documentation I am writing!
